version: '2'

volumes:
  drupal_source:
    external: true

services:
  mysql:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    ports:
      - "3306:3306"

  php:
    image: blauerberg/drupal-php:5.6-fpm
    volumes:
      - drupal_source:/var/www/html
    links:
      - mysql

  nginx:
    image: nginx:1.10
    links:
      - php
    volumes:
      - drupal_source:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
